### ISSUE TITLE
Wrong about the computational complexity

### ISSUE THREAD

**Issue by Med-Process** [google-research/maxim#15]
![image](https://user-images.githubusercontent.com/57434913/165428991-b9b62b45-20aa-4d52-91ab-a49f1897db07.png)

Here, for dense layers, the computational complexity should be: d^2HW(C/2) + b^2HW(C/2) + 3HWC^2

**Comment by vztu** [comment]
Given the input feature H,W,C, the whole Multi-axis gMLP block (figure 3) has: `Input proj (2HWC^2) + Output proj (2HWC^2) + Block-gMLP dense (3HWC^2) + Grid-gMLP dense (3HWC^2) = 10HWC^2`

Note: the first Dense layer in gMLP block expands channels from C to 2C, thus 2HWC^2. Output Dense in gMLP is HWC^2. So the whole gMLP block has 3HWC^2.

**Comment by Med-Process** [comment]
I see. Thank you. But, the figure 3 is confused with C and C / 2.

**Comment by vztu** [comment]
Oh yeah you're right. We follow common complexity convention from Swin, etc, but didn't expect to cause a confusion.
