### ISSUE TITLE
Train my own model using maxim.py

### ISSUE THREAD

**Issue by zarmondo11** [google-research/maxim#17]
Hello and thank you for your insane paper...
I have a question... How can I train my own model instead of using checkpoints?

**Comment by vztu** [comment]
We don't have any plans to release the Jax training pipeline, unfortunately. However, we plan to reproduce the model in PyTorch and release the training/validation code [here](https://github.com/vztu/maxim-pytorch). The repo is still under construction, but I am busy with graduation stuff recently, so please stay tuned...

**Comment by zarmondo11** [comment]
Thank you but I will ask another question in pytorch rep.
