### ISSUE TITLE
No GPU found

### ISSUE THREAD

**Issue by hs0817** [google-research/maxim#21]
Hello, I installed the environment and projects according to requirements. txt, but there was no GPU in the test process. My CUDA version was 11.2, and the GPU was RTX3090. Can you help me explain this situation?
![1659858182299](https://user-images.githubusercontent.com/64005314/183280692-a28e85cb-0036-4d52-8ca6-cdf2175f8130.png)

**Comment by Walterfdh** [comment]
You should use the jaxlib's cuda version.

**Comment by hs0817** [comment]
Thank you for your quick response.
