### ISSUE TITLE
TensorFlow/Keras port

### ISSUE THREAD

**Issue by sayakpaul** [google-research/maxim#30]
@vztu @Yinxiaoli 

I worked on porting all the public MAXIM models to TensorFlow: https://github.com/sayakpaul/maxim-tf.

There are some WIPs: inference Colab, polished README, etc. Actively working on those. 

Here, one can find all the ported SavedModels: `gs://maxim-tf`. 

Additionally, I have created several Space applications on Hugging Face for better interactivity with the models:

* [Denoising](https://huggingface.co/spaces/sayakpaul/sidd-denoising-maxim)
* [Low-light enhancement](https://huggingface.co/spaces/sayakpaul/lol-enhancement-maxim)
* [Dehazing indoors](https://huggingface.co/spaces/sayakpaul/sots-indoor-dehazing-maxim)
* [Dehazing outdoors](https://huggingface.co/spaces/sayakpaul/sots-outdoor-dehazing-maxim)

Will be adding the rest in the coming days. **Would you be willing you to add a line about the TF repository from the README?** I will be publishing the TF ported models on TensorFlow Hub too. As of today, they're available on Hugging Face: https://huggingface.co/sayakpaul. 

@innat I also saw #29. Seems like we both started working on porting the models. If you're interested, you can contribute the rest of the Spaces applications. 

Cc: @gustheman

**Comment by sayakpaul** [comment]
Sure. If the KerasCV team includes it in the ROADMAP, I don't see any problems. But we can always revisit it. Thanks for the support :)

**Comment by innat** [comment]
As no implementation cost from scratch, I think it shouldn't be a problem. 
@LukeWood @tanzhenyu

**Comment by vztu** [comment]
Thanks a lot for these great efforts @sayakpaul @innat! 
We'll be updating the README to acknowledge your codebase as well as huggingface spaces soon. Please let us know if you need any supports on our side.

**Comment by sayakpaul** [comment]
Thank you :)

**Comment by sayakpaul** [comment]
Thanks for mentioning the project. Would you also mind mentioning Space application links?

**Comment by vztu** [comment]
Sure, glad to do that. I found you have multiple spaces for each task. Could you make it more unified so that I only need to add a single link? Or you can summarize them in your README file and I point to that.

**Comment by sayakpaul** [comment]
I created a PR: https://github.com/google-research/maxim/pull/33

**Comment by vztu** [comment]
Merged. Thank you!

**Comment by sayakpaul** [comment]
Thanks!
