### ISSUE TITLE
problem about maxim 

### ISSUE THREAD

**Issue by woaicv** [google-research/maxim#4]
Hi, thank you very much for your work! I currently want to learn your approach, but because my code level is not very good, I need to run through it a little bit. I can follow your run_eval, but when I add some output in MAXIM, there is no corresponding output after execution. What I would like to ask you is how to perform forward propagation and print out some desired results during the forward propagation process, which is conveni
<img width="499" alt="WeChat92cdd69c7905f13f59663c879c680e62" src="https://user-images.githubusercontent.com/90394190/161905366-c1a451d3-e50d-4785-a6a4-fe7ca95dafbd.png">
ent for learning. Hope to get your answer, thank you very much🙏

**Comment by vztu** [comment]
Hi, you should run setup again if any modifications have been made.

Run `pip install .` again. Then you will see the logs.

**Comment by woaicv** [comment]
Ok, thanks a lot for your reply. The frameworks I have seen before are written in the forward format, so looking at your code will cause some problems. The multiple Unsamples in the figure below, Con1x1, Con3x3, do not share weights, right? Looking forward to your repl
![221649288149_ pic](https://user-images.githubusercontent.com/90394190/162091574-6f3e7fd6-0fee-4506-b76d-2d10460ae4d6.jpg)
![231649288319_ pic](https://user-images.githubusercontent.com/90394190/162091584-e1ac566f-8fb8-4ae3-b4c6-15e10000ae82.jpg)
y

**Comment by vztu** [comment]
Yes, they're not sharing weights. BTW, we've set `self.use_cross_gating = True` by default. So the `else:` part is not reached.

**Comment by woaicv** [comment]
Ok, thank you very much. Does pixelshuffle and pixelunshuffle for unsample downsample have little effect on performance?

**Comment by vztu** [comment]
I haven't tried those alternatives. But I feel that it doesn't matter that much whichever downsample/upsample methods you use, as it is a UNet architecture and has long skip connects. You may have to try and see how performance varies.
