### ISSUE TITLE
Would you consider using Pytorch to achieve this project?

### ISSUE THREAD

**Issue by Wang-Kaige** [google-research/maxim#7]
I think that using Pytoch to achieve this project again would significantly increase the impact of this project and I would appreciate your consideration!

**Comment by vztu** [comment]
Hi, Thanks for your suggestion. I'll think about implementing it in PyTorch if I have some time recently.

**Comment by Wang-Kaige** [comment]
Github and Zhihu are really same-sex dating sites! Your research experience (from IC to CV) and research direction are amazingly consistent with mine, and I am reading your explanation of this article on Zhihu. The proliferation of articles makes it obvious to me that this field is getting more and more followers in recent years,  too difficult to follow.
